### ISSUE TITLE
Android: App not working on Android 11 due to external storage permission issues

### ISSUE THREAD

**Issue by augustin-colesnic** [ezra-bible-app/ezra-bible-app#322]
After installing the Ezra Bible App  on Android Samsung Galaxy Tab 6 Lite it took a long wait time to initialise user interface over 5 min... and I stoped waiting.  Most probably it just stoped working.

![Screenshot_20210529-071008_Ezra Bible App](https://user-images.githubusercontent.com/592416/120059860-ca63e280-c05c-11eb-88f6-728caf1751e6.jpg)
![Screenshot_20210529-071031_Ezra Bible App](https://user-images.githubusercontent.com/592416/120059861-cb950f80-c05c-11eb-8343-d27186e78730.jpg)
![Screenshot_20210529-071343_Ezra Bible App](https://user-images.githubusercontent.com/592416/120059862-cc2da600-c05c-11eb-8528-63ab30460126.jpg)
![Screenshot_20210529-071439_Google Play Store](https://user-images.githubusercontent.com/592416/120059863-cc2da600-c05c-11eb-8a77-a29ab2f2d3ea.jpg)

**Comment by tobias-klein** [comment]
Thanks for this bug report!
This is most probably a bug in the startup sequence. It should not take more than 10-15s to load on an Android tablet.

Would you mind doing the following for debugging:
1. Install Android Platform Tools to get the add command line tool (On macOS it would be `brew install android-platform-tools`).
2. Enable developer mode on the tablet.
3. Enable USB debugging.
4. Connect via USB.
5. Run `adb logcat > debug.txt`
6. Attempt to start the app

Then after waiting a minute we should have a debug log file. Could you attach that here? It would be very helpful!

**Comment by augustin-colesnic** [comment]
Here it is @tobias-klein 
[debug-ezra-bible-app-android.txt](https://github.com/ezra-bible-app/ezra-bible-app/files/6565675/debug-ezra-bible-app-android.txt)

**Comment by tobias-klein** [comment]
Here is the section from that logfile that explains things.

```
05-30 07:07:01.029 24882 24882 D SystemWebChromeClient: file:///android_asset/www/dist/ezra_init.js: Line 12667 : load event fired!
05-30 07:07:01.029 24882 24882 D SystemWebChromeClient: file:///android_asset/www/dist/ezra_init.js: Line 14427 : Initializing app on Cordova platform ...
05-30 07:07:01.036 24882 24882 D SystemWebChromeClient: file:///android_asset/www/dist/ezra_init.js: Line 14443 : Configuring Sentry (WebView) with app version: 1.0.0
05-30 07:07:01.069 24882 24882 D SystemWebChromeClient: file:///android_asset/www/dist/ezra_init.js: Line 21387 : Starting up nodejs engine!
05-30 07:07:01.073  4700  4700 E audit   : type=1327 audit(1622347621.069:235): proctitle="net.ezrabibleapp.cordova"
05-30 07:07:01.808 24882 24882 D SystemWebChromeClient: file:///android_asset/www/dist/ezra_init.js: Line 21387 : nodejs: main.js loaded
05-30 07:07:01.814 24882 24882 D SystemWebChromeClient: file:///android_asset/www/dist/ezra_init.js: Line 13902 : getTranslation: 717.179931640625 ms
05-30 07:07:01.864 24882 26215 I NODEJS-MOBILE: Creating data directory for app at /sdcard/Android/data/net.ezrabibleapp.cordova
05-30 07:07:01.878 24882 26216 E NODEJS-MOBILE: Error: EACCES: permission denied, mkdir '/sdcard/Android/data/net.ezrabibleapp.cordova'
05-30 07:07:01.878 24882 26216 E NODEJS-MOBILE:     at Main.initStorage (/data/user/0/net.ezrabibleapp.cordova/files/www/nodejs-project/main.js:93:10)
05-30 07:07:01.878 24882 26216 E NODEJS-MOBILE:     at Main.initPersistentIpc (/data/user/0/net.ezrabibleapp.cordova/files/www/nodejs-project/main.js:59:10)
05-30 07:07:01.878 24882 26216 E NODEJS-MOBILE:     at /data/user/0/net.ezrabibleapp.cordova/files/www/nodejs-project/app/backend/ipc/ipc_general_handler.js:32:28
05-30 07:07:01.878 24882 26216 E NODEJS-MOBILE:     at EventChannel.<anonymous> (/data/user/0/net.ezrabibleapp.cordova/files/www/nodejs-project/app/backend/ipc/ipc_main.js:72:33)
05-30 07:07:01.878 24882 26216 E NODEJS-MOBILE:     at Immediate.<anonymous> (/data/user/0/net.ezrabibleapp.cordova/files/nodejs-mobile-cordova-assets/builtin_modules/cordova-bridge/index.js:68:13)
05-30 07:07:05.865  5089 11518 D GameManagerService: identifyGamePackage. net.ezrabibleapp.cordova, mCurrentUserId: 0, callerUserId: 0
05-30 07:07:05.865  5089 11518 D PkgDataHelper: getGamePkgData(). net.ezrabibleapp.cordova
05-30 07:07:17.712 24882 24882 D SystemWebChromeClient: file:///android_asset/www/dist/ezra_init.js: Line 21387 : Did not get node response for general_initPersistentIpc
05-30 07:07:17.713 24882 24882 D SystemWebChromeClient: file:///android_asset/www/dist/ezra_init.js: Line 13829 : initPersistentIpc: 15853.431884765625 ms
05-30 07:07:18.242 24882 26216 E NODEJS-MOBILE:     at DbHelper.getDatabaseDir (/data/user/0/net.ezrabibleapp.cordova/files/www/nodejs-project/app/backend/helpers/db_helper.js:70:41)
05-30 07:07:18.242 24882 26216 E NODEJS-MOBILE:     at IpcDbHandler.initDatabase (/data/user/0/net.ezrabibleapp.cordova/files/www/nodejs-project/app/backend/ipc/ipc_db_handler.js:40:27)
05-30 07:07:18.242 24882 26216 E NODEJS-MOBILE:     at IPC.initDatabase (/data/user/0/net.ezrabibleapp.cordova/files/www/nodejs-project/app/backend/ipc/ipc.js:80:24)
05-30 07:07:18.242 24882 26216 E NODEJS-MOBILE:     at Main.initDatabase (/data/user/0/net.ezrabibleapp.cordova/files/www/nodejs-project/main.js:67:16)
05-30 07:07:18.242 24882 26216 E NODEJS-MOBILE:     at /data/user/0/net.ezrabibleapp.cordova/files/www/nodejs-project/app/backend/ipc/ipc_general_handler.js:36:28
05-30 07:07:18.242 24882 26216 E NODEJS-MOBILE:     at EventChannel.<anonymous> (/data/user/0/net.ezrabibleapp.cordova/files/www/nodejs-project/app/backend/ipc/ipc_main.js:72:33)
05-30 07:07:18.242 24882 26216 E NODEJS-MOBILE:     at Immediate.<anonymous> (/data/user/0/net.ezrabibleapp.cordova/files/nodejs-mobile-cordova-assets/builtin_modules/cordova-bridge/index.js:68:13)
05-30 07:07:18.260 24882 24882 D SystemWebChromeClient: file:///android_asset/www/dist/ezra_init.js: Line 13837 : initDatabase: 546.552978515625 ms
05-30 07:07:18.273 24882 24882 D SystemWebChromeClient: file:///android_asset/www/dist/ezra_init.js: Line 21387 : Loading HTML fragments
05-30 07:07:18.430 24882 24882 D SystemWebChromeClient: file:///android_asset/www/dist/ezra_init.js: Line 21387 : Initializing IPC clients ...
05-30 07:07:22.789 24882 24882 D SystemWebChromeClient: file:///android_asset/www/dist/ezra_init.js: Line 21387 : Did not get node response for settings_get
05-30 07:07:22.792 24882 24882 D SystemWebChromeClient: file:///android_asset/www/dist/ezra_init.js: Line 21387 : Initializing i18n ...
05-30 07:07:22.820 24882 24882 D SystemWebChromeClient: file:///android_asset/www/dist/ezra_init.js: Line 21387 : Initializing controllers ...
05-30 07:07:27.163 24882 24882 D SystemWebChromeClient: file:///android_asset/www/dist/ezra_init.js: Line 21387 : Did not get node response for nsi_strongsAvailable
05-30 07:07:27.166 24882 24882 D SystemWebChromeClient: file:///android_asset/www/dist/ezra_init.js: Line 21387 : Did not get node response for settings_get
05-30 07:07:31.512 24882 24882 D SystemWebChromeClient: file:///android_asset/www/dist/ezra_init.js: Line 21387 : Did not get node response for settings_get
05-30 07:07:35.862 24882 24882 D SystemWebChromeClient: file:///android_asset/www/dist/ezra_init.js: Line 21387 : Did not get node response for settings_has
05-30 07:07:35.862 24882 24882 D SystemWebChromeClient: file:///android_asset/www/dist/ezra_init.js: Line 21387 : Localizing book selection menu ...
05-30 07:07:40.174 24882 24882 D SystemWebChromeClient: file:///android_asset/www/dist/ezra_init.js: Line 21387 : Did not get node response for nsi_getSwordTranslation
05-30 07:07:44.496 24882 24882 D SystemWebChromeClient: file:///android_asset/www/dist/ezra_init.js: Line 21387 : Did not get node response for nsi_getSwordTranslation
05-30 07:07:48.826 24882 24882 D SystemWebChromeClient: file:///android_asset/www/dist/ezra_init.js: Line 21387 : Did not get node response for nsi_getSwordTranslation
```

The root-cause is that we cannot write to /sdcard/Android and this renders the app dysfunctional ...

```
05-30 07:07:01.864 24882 26215 I NODEJS-MOBILE: Creating data directory for app at /sdcard/Android/data/net.ezrabibleapp.cordova
05-30 07:07:01.878 24882 26216 E NODEJS-MOBILE: Error: EACCES: permission denied, mkdir '/sdcard/Android/data/net.ezrabibleapp.cordova'
```

@augustin-colesnic 
Can you check with a file manager app whether the directory /sdcard/Android/data exists on your tablet?

**Comment by tobias-klein** [comment]
Writing to /sdcard is enabled with the permission `MANAGE_EXTERNAL_STORAGE` (see [here](https://developer.android.com/training/data-storage/manage-all-files#operations-allowed-manage-external-storage)), which is requested initially by the app.
Can you check in the app details of Android whether that permission has been granted successfully?

Otherwise you can enforce that permission like this (while the device is connected to your computer via usb) and try startup once more:
`adb shell appops set --uid net.ezrabibleapp.cordova MANAGE_EXTERNAL_STORAGE allow`

**Comment by tobias-klein** [comment]
Just for completeness ... which Android version are you running on your tablet?

**Comment by tobias-klein** [comment]
What is the output of this command?

```
adb shell 'echo ${SECONDARY_STORAGE%%:*}'
```

**Comment by tobias-klein** [comment]
I could reproduce this on Android 11 in the emulator! It seems like an issue only happening with Android 11!

**Comment by tobias-klein** [comment]
The permissions model for external storage is changing from Android 11 and this is causing issues.
Moving to the new _scoped storage_ would require major efforts. For the time being we should rather use the internal storage instead if the external one (/sdcard) is not writable. That's the approach that I would like to take to fix this bug. Essentially this means to implement a different startup behavior from Android 11 and newer versions.

**Comment by tobias-klein** [comment]
I implemented a work-around to use internal storage from Android 11 and following ... I am planning to release a bugfix release next week!

**Comment by augustin-colesnic** [comment]
> Just for completeness ... which Android version are you running on your tablet?

I am using Android 11

**Comment by augustin-colesnic** [comment]
Let me know when you release it to Play Store. Thanks a lot!

**Comment by tobias-klein** [comment]
Just pushed 1.0.1 to the Play Store but it's only going to be available there a few days from now once the Google folks have checked the new release.

**Comment by tobias-klein** [comment]
@augustin-colesnic
1.0.1 is now available in the Play Store! Check it out!
