### ISSUE TITLE
Issue installing on Librem5

### ISSUE THREAD

**Issue by programmin1** [ezra-bible-app/ezra-bible-app#643]
There's an issue installing this on the Librem phone. I tried the debian, Debian11 and Ubuntu .deb files (why are there three??),

none would install and using dpkg -i ezra.deb file I could see the reason, these are build for amd64, and not ARM64.

When can we get some ARM64 builds please?

**Comment by tobias-klein** [comment]
I didn't know about the Librem phone, I first had to google it. How big is the screen of that phone? The app is not made for small screens. Anything below 7" is not suitable with the currently available UI. If you want an ARM build, the first thing that comes to my mind is: Does Electron support that?

Regarding the different Deb files, it is for different versions of Ubuntu.

**Comment by programmin1** [comment]
I suppose I can try the build steps and see... 
You never heard of Libremphone/pinephone? There are also other Linux phones - https://linuxstans.com/linux-phone/ and they are probably going to become more popular considering what's happening with Apple/Google lately - did you see the latest issues with security, that they are not patching on all but the latest phones? https://www.securityweek.com/androids-march-2022-security-updates-patch-39-vulnerabilities

**Comment by tobias-klein** [comment]
I knew that there were some independent Linux based projects, but I had not heard about this particular one.

Give it a try. Contributions are welcome. However, please consider the constraints about the UI on small screens.

**Comment by programmin1** [comment]
I got it to build but now I have this error on "npm start":
```
npm start

> ezra-bible-app@1.6.0-Dev start /home/purism/ezra-bible-app
> electron .

Working with userDataPath /home/purism/.config/ezra-bible-app
Using settings file /home/purism/.config/ezra-bible-app/config.json
[29282:0312/232819.399783:ERROR:web_contents_preferences.cc(261)] preload script must have absolute path.
[29314:0312/232819.974203:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[29361:0312/232820.116764:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
Using default database dir /home/purism/.config/ezra-bible-app for database access!
Initializing database at /home/purism/.config/ezra-bible-app
Error occurred in handler for 'initIpc': Error: Please install sqlite3 package manually
    at ConnectionManager._loadDialectModule (/home/purism/ezra-bible-app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:88:15)
    at new ConnectionManager (/home/purism/ezra-bible-app/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:22:21)
    at new SqliteDialect (/home/purism/ezra-bible-app/node_modules/sequelize/lib/dialects/sqlite/index.js:14:30)
    at new Sequelize (/home/purism/ezra-bible-app/node_modules/sequelize/lib/sequelize.js:334:20)
    at DbHelper.getSequelize (/home/purism/ezra-bible-app/app/backend/database/db_helper.js:112:21)
    at DbHelper.migrateDatabase (/home/purism/ezra-bible-app/app/backend/database/db_helper.js:117:26)
    at DbHelper.initDatabase (/home/purism/ezra-bible-app/app/backend/database/db_helper.js:40:16)
    at IpcDbHandler.initDatabase (/home/purism/ezra-bible-app/app/backend/ipc/ipc_db_handler.js:52:20)
    at IPC.initDatabase (/home/purism/ezra-bible-app/app/backend/ipc/ipc.js:81:31)
    at IPC.init (/home/purism/ezra-bible-app/app/backend/ipc/ipc.js:74:20)
    at /home/purism/ezra-bible-app/main.js:140:24
```
