### ISSUE TITLE
Bug: Can't run on Arch Linux with AUR packages

### ISSUE THREAD

**Issue by joshpetit** [ezra-bible-app/ezra-bible-app#707]
I'm using Arch linux and installed ezra through the `ezra-bible-app-git` package on the aur. This is the output I get when trying to run it the first time:

```
Working with userDataPath /home/joshu/.config/ezra-bible-app
Using settings file /home/joshu/.config/ezra-bible-app/config.json
[69859:0629/080110.833075:ERROR:web_contents_preferences.cc(259)] preload script must have absolute path.
Using default database dir /home/joshu/.config/ezra-bible-app for database access!
Initializing database at /home/joshu/.config/ezra-bible-app
Error occurred in handler for 'initIpc': Error: Please install sqlite3 package manually
    at ConnectionManager._loadDialectModule (/usr/lib/ezra-bible-app/resources/app.asar/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:88:15)
    at new ConnectionManager (/usr/lib/ezra-bible-app/resources/app.asar/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:22:21)
    at new SqliteDialect (/usr/lib/ezra-bible-app/resources/app.asar/node_modules/sequelize/lib/dialects/sqlite/index.js:14:30)
    at new Sequelize (/usr/lib/ezra-bible-app/resources/app.asar/node_modules/sequelize/lib/sequelize.js:334:20)
    at DbHelper.getSequelize (/usr/lib/ezra-bible-app/resources/app.asar/app/backend/database/db_helper.js:112:21)
    at DbHelper.migrateDatabase (/usr/lib/ezra-bible-app/resources/app.asar/app/backend/database/db_helper.js:117:26)
    at DbHelper.initDatabase (/usr/lib/ezra-bible-app/resources/app.asar/app/backend/database/db_helper.js:40:16)
    at IpcDbHandler.initDatabase (/usr/lib/ezra-bible-app/resources/app.asar/app/backend/ipc/ipc_db_handler.js:52:20)
    at IPC.initDatabase (/usr/lib/ezra-bible-app/resources/app.asar/app/backend/ipc/ipc.js:81:31)
    at IPC.init (/usr/lib/ezra-bible-app/resources/app.asar/app/backend/ipc/ipc.js:74:20)
    at /usr/lib/ezra-bible-app/resources/app.asar/main.js:147:24
    at node:electron/js2c/browser_init:189:579
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:11093)
    at EventEmitter.emit (node:events:390:28)
```
Then all I see is "loading..." on the screen 

When I try running the `ezra-bible-app-bin` package from the aur I receive this error:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libicuio.so.suse65.1: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1800)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1800)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/lib/ezra-bible-app/resources/app/node_modules/node-sword-interface/index.js:20:34)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
```

When I try running the `ezra-bible-app` package from the aur I receive this error:

```
Using settings file /home/joshu/.config/ezra-bible-app/config.json
[76850:0629/081336.711489:ERROR:web_contents_preferences.cc(259)] preload script must have absolute path.
```

This app is something I'm really looking forward to using so I'd appreciate any help in getting it running!

**Comment by tobias-klein** [comment]
@joshpetit 
Thank you for reporting this issue!
This is actually already tracked here:
https://github.com/alerque/aur/issues/23

@alerque 
I believe this is known, right. Can you have a look based on my comments in the issue linked above?

**Comment by joshpetit** [comment]
Ah I see, sorry should've done a search first
